### ISSUE TITLE
Enso_ex reliable or not

### ISSUE THREAD

**Issue by silverizer** [SKGleba/enso_ex#12]
Hi there my friend. Im a member of a facebook group PSP PS VITA Hacks & Mods
somehow the people there dont really recommend the Enso_ex because of the number of people having issues after the installation from 3.65 enso. 
I am one of those who have tried and took the risk. My only goal for the upgrade is to change the boot up animation. 

I encountered several issues like losing the access with the Henkaku settings but was able to recover access after reinstalling Henkaku thru H-encore. I was able to this because I backed up the app to my content manager prior the upgrade and have also installed vitashell in my system app with the use of HB injector app. I also managed to back up my ur0:tai/ folder within ur0:

I was able to successfully restore everything back and got my boot animation working well without any issues. up until today I dont have any issues with my vita. 

I just would like to suggest if you can include the "**warning message**" in the Enso ex options page for Sd2vita driver and a **confirmation message** that you can go back if you want to undo the selection would really be helpful. By doing this, this would avoid future issues after installtion of Enso_ex that would cause possible brick.

Youre response will be greatly appreciated.

Ps here is my Enso_Ex boot animation.
https://www.facebook.com/g551jw/videos/1064620120595591/

**Comment by SKGleba** [comment]
The new ver will be completely different, so i wont edit the old one for now.

**Comment by SKGleba** [comment]
nice animation tho

**Comment by silverizer** [comment]
Thank you
