### ISSUE TITLE
I semi bricked my psvita

### ISSUE THREAD

**Issue by nounzein** [SKGleba/enso_ex#13]
Hi,

I used your tool to restablich the playstation logo after i installed the official Ensio for 3.65.
I disabled the sd2vita driver and enabled the Update blocker.
Now every time i start my vita it ask me to format my memory card and even if i do it i got the same message again and again.
I tried to restore the system but it didn't work, i tried to reinstal an ofw and it's also blocked.
The only think that gives me hope is that i injected vitashell in near buble before all that and it's still working. but i can't modify or delete any file

Any help it's a psvita 1000 3g model

**Comment by SKGleba** [comment]
Reinstall the firmware. To bypass the lock connect the vita to a charger (NOT pc) when the PUP is copied and EULA appears.

**Comment by nounzein** [comment]
i'll try this thanks

**Comment by chronoss09** [comment]
This help me, thanks a lot :)

**Comment by nounzein** [comment]
This worked for thanks a lot
