### ISSUE TITLE
Error compiling with create_vpk script (ver4.1 April 13)

### ISSUE THREAD

**Issue by Introvert52** [SKGleba/enso_ex#15]
Screenshot attached. I tried compiling from master and also from source attached with 4.1 release. Using Ubuntu 18.04 with VITASDK properly installed and listed in .bashrc as variable and in $PATH. Latest YAMT compiles fine with the script included with it. Apologies if I'm just being stupid.

![eex_compile](https://user-images.githubusercontent.com/49093895/79128542-1ef6c080-7dbd-11ea-9f25-bd29104150b6.png)

**Comment by SKGleba** [comment]
Latest vitasdk commits broke older scripts. I will try to port it in next ver.

**Comment by SKGleba** [comment]
will be fixed in v4.5

**Comment by SKGleba** [comment]
Fixed in v4.5
