### ISSUE TITLE
“Henkaku version is too old”

### ISSUE THREAD

**Issue by ScareFeratis** [SKGleba/enso_ex#16]
Hello. I’m trying to migrate from 3.60 to 3.65 to proceed with your Hybrid FW manual and tools. I used TheFloW’s script to update. Now, when I’m trying to install Enso Ex, I’m getting “Your henkaku version is too old”.

AFAIK, there’s no way to update Henkaku except of returning to stock and running H-Encore. Should I do that or it is a bug on your side?

**Comment by SKGleba** [comment]
Yeah, as stated in https://github.com/SKGleba/enso_ex/blob/master/README.md#installing , you need to have enso v1.1, the one you have is update365 enso v1.0.

Your best bet would be to reinstall the firmware and install fresh hencore & henkaku; you need a memory card for that.
