### ISSUE TITLE
v4.1: Failed to get fw version

### ISSUE THREAD

**Issue by therealsamsquanch** [SKGleba/enso_ex#17]
I had an older version of enso_ex installed (v3.0?) and it was working fine. 

I downloaded the latest v4.1, transferred to my Vita 1001 and installed the vpk without uninstalling the previous version or the bubble. When I open it and proceed after the warning, it tells me right away that it "failed to get fw version". I'm on 3.65. Uninstalled enso_ex's bubbles, installed again, disabled FW spoof and tried again, but I got the same message. I didn't rebooted between any of the procedures I listed. 

Since it didn't do anything, it's safe to reboot, right? Any logs that I can provide to help with the error it is reporting?

Thank you! :)

**Comment by SKGleba** [comment]
Boot without any plugins (as stated in the readme). It is probably 0syscall6's fault.

**Comment by betho225** [comment]
how would i boot without any plugins tho
