### ISSUE TITLE
Can't use Content manager & internet memory PSV2000

### ISSUE THREAD

**Issue by i4mout** [SKGleba/enso_ex#2]
As the title... 
I removed enso (theflow) and installed enso_ex and now i can't do anything :( 
I'm stuck at 3.65 and Content manager says "You need a memory card" 
Internal memory 0GB Free? 0GB available ... 

Pls Help :(

**Comment by BombBloke** [comment]
Do you have an SD2Vita? Did you enable the SD2Vita driver during installation?

**Comment by i4mout** [comment]
Yup! i have sd2vita, I restored the vita twice ... Now, I can use homebrews, BUT, Henkaku Settings dissapeared, and H-Encore, crash every time :/, .... need unsafe option to uninstall enso :(

**Comment by i4mout** [comment]
Fw reinstalled and fixed
