### ISSUE TITLE
Known MBR checksums only contains 3.60 MBR checksums

### ISSUE THREAD

**Issue by dogtopus** [SKGleba/enso_ex#20]
So I got a warning when I install enso_ex over 3.65 enso (aka TheOfficialFlow enso) saying the MBR checksum is unknown despite the README saying it also works when installing over 3.65 enso (and it surely works well). Not really a big issue but surely scary for a moment.

According to the [source](https://github.com/TheOfficialFloW/enso/blob/f012c27cead1df88fde11f4849d88f0e9a0710a2/installer/src/kernel.c#L376) they should be
```c
uint32_t known_crc[] = { 0xa6b37650, 0x723111d1 };
```

**Comment by SKGleba** [comment]
I will just remove it in v4.2, it anyways false flags even on retail installer.

**Comment by SKGleba** [comment]
Fixed in v4.5
