### ISSUE TITLE
Enso blocked in PS logo and reboot

### ISSUE THREAD

**Issue by BenMitnicK** [SKGleba/enso_ex#23]
I make some test with my 2 vita slim and fat

Sometimes It blocked in PS logo and reboot and Always when I installed plugins and reboot enso blocked in PS logo and reboot after this it's ok

Why ? 

Apart from this problem everything seems to work well

But CBSM does not display my animation correctly while with the old enso no problem so I came back under enso 3.1 with delay. In addition I have some special 10s animation so enso 3.1 for me. it would be nice to make a version 4.1 with animation and delay for the peoples who want it like me. Me personally I activate the delay and deactivate udcd then I deactivate the delay and activate udcd it works very nice

**Comment by SKGleba** [comment]
Enso is before the bootlogo so your issue is plugin-related. If you see the bootlogo it means enso_ex v4 works.
