### ISSUE TITLE
Brick with self compiled bootmgr, recovery, fwspoof?

### ISSUE THREAD

**Issue by unresolvedsymbol** [SKGleba/enso_ex#30]
Was attempting preparation for psp2hfw (got to step 5, beginning step 6 but couldn't sync so I disabled 0syscall6 rebooted and synced, it said everything was alright) and before continuing I was going to test recovery mode just to be on the safe side, looks like I screwed up because now this device won't do anything but blink orange (until I reconnect the battery) or stay solid green... I was trying the charger + select + power to enter recovery mode, I saw safe mode once when holding the power button long enough but now I can't reproduce that (even with power + home + r). This device is a slim with 3.65, recovery is file based on internal ux0.
I know this was completely on me, I appreciate all your work developing these tools.
Just opening to see if anyone has suggestions, thanks.

**Comment by unresolvedsymbol** [comment]
Wow should've used recoVery, didn't know this existed x_x hopefully once my sd2vita arrived I can try to boot it

**Comment by unresolvedsymbol** [comment]
Unsolved, console scrapped :p

**Comment by SKGleba** [comment]
You could try recoVery or the os0_flash.e2xp that reflashes os0 from the sd card.
Also i didnt see this issue (github doesnt notify for some reason), sorry for not checking earlier.
