### ISSUE TITLE
original psvita logo

### ISSUE THREAD

**Issue by gromber** [SKGleba/enso_ex#31]
please, add a option to have original psvita logo, i cant find Molecule's boot logo disabler for enso (3.65) and i don´t know if it´s compatible with enso_ex.

thanks for all your work.

**Comment by SKGleba** [comment]
Remove ux0:eex/custom/bootlogo.raw & e2xculogo.skprx and then sync via the enso_ex installer.

**Comment by gromber** [comment]
hi, that solution removes all logos.

**Comment by SKGleba** [comment]
removing e2xculogo.skprx removes logo patches so it should be back to the PS logo.

**Comment by gromber** [comment]
Maybe I did it wrong, because i installed enso_ex with official psvita card, and then changed to sd2vita so i copied again that custom folder, but now i have a psvita fat with no logo.
