### ISSUE TITLE
Henkaku doesn't load

### ISSUE THREAD

**Issue by NekoMimiOfficial** [SKGleba/enso_ex#32]
I've successfully managed to install enso ex
Disabled all plugins before install
And just went with the vpk

When I reboot it shows a new boot image but henkaku never loads
I've checked the boot config
-load ur0:tai/henkaku.skprx
The line above is present, I've even tried to redo my hencore2 henkaku tai plugin setup and tried to sync the boot config file
Non worked

**Comment by NekoKitsune** [comment]
Nevermind apparently the boot_config file was never created in ur0 instead it only exists in ux0:eex/
I'm not gonna close this issue because I'm not sure if this is intentional
