### ISSUE TITLE
did you give up on the project?

### ISSUE THREAD

**Issue by Sal-gamer** [SKGleba/enso_ex#33]
I would like the update that will only work on 3.65, as it is in the notice below for the latest enso ex version news, I am looking forward and waiting for news, I keep promoting your enso for being the best, it has a beautiful logo, I have never had plugin conflicts, as I have had in 3.65 update or 3.60 / 3.65 normal, I've never had loop like I've had in the others, it's fluid, your ex enso is amazing, so I really wanted an update that you said will only arrive in 3.65.

**Comment by SKGleba** [comment]
it will get updated, the new version simply doesnt have enough new features yet to warrant a full release
