### ISSUE TITLE
Can I update my enso psvita by playstation

### ISSUE THREAD

**Issue by Ilonmasko** [SKGleba/enso_ex#34]
I have a jailbreak psvita on enso. One day I work with MaiDumpTool and the data transfer had problems. I deleted the data and want to try again but the folder was corrupted and said it is now a directory. From this point on vitashel often doesn't open anymore and sad something like (please in insert a card for this application ore normal error). After this I came on the dumm idea to go into safe mode and recover the system. This fuck alle up. I have no application anymore. I go into contact manager to copy vitashel on psvita but it didn't let me and give me error codes when I wait 10 sec after I press on connect pair usb. Now I connect it to the WiFi and it start to ask to log in with ps account to transfer data. When I do it still give me error after words. It always say to update the System to log in in ps. Can I fix it oder should I update it?

**Comment by SKGleba** [comment]
you can update
